services:
  - type: web
    name: ai-resume-analyzer
    env: python
    buildCommand: "pip install -r requirements.txt && python -m spacy download en_core_web_sm && python database/init_db.py"
    startCommand: "gunicorn app:app"
    plan: free